# ============================================================================ #
#                Docker Build   ->   Docker HUB
# ============================================================================ #

# Docker Build, Tag & Push to Docker Hub

    name: Docker-Build-to-Docker-Hub
    
    on:
      pull_request:
        branches: main

    jobs:
      build_docker:
        name: Docker-Build-to-Docker-Hub
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
    
          - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
    
        #   - name: Docker Build & Push
        #     uses: docker/build-push-action@v2
        #     with:
        #       context: .
        #       file: ../../DockerFile
        #       push: true
        #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/fp-manager:latest
        #       build-args: |
        #         NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
        #         NEXT_PUBLIC_MONGODB_URI=${{ secrets.NEXT_PUBLIC_MONGODB_URI }}